{% set version = "1.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ps
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ps_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ps/ps_{{ version }}.tar.gz
  sha256: 8468c6994e199053050c614fb3e6ee0e670833a0185abf53d6cb09e19c85aeb3

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('ps')"           # [not win]
    - "\"%R%\" -e \"library('ps')\""  # [win]

about:
  home: https://github.com/r-lib/ps#readme
  license: BSD_3_clause
  summary: List, query and manipulate all system processes, on 'Windows', 'Linux' and 'macOS'.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ps
# Version: 1.3.1
# Title: List, Query, Manipulate System Processes
# Description: List, query and manipulate all system processes, on 'Windows', 'Linux' and 'macOS'.
# Authors@R: c( person("Jay", "Loden", role = "aut"), person("Dave", "Daeschler", role = "aut"), person("Giampaolo", "Rodola'", role = "aut"), person("Gabor", "Csardi", , "csardi.gabor@gmail.com", c("aut", "cre")), person("RStudio", role = "cph"))
# License: BSD_3_clause + file LICENSE
# URL: https://github.com/r-lib/ps#readme
# BugReports: https://github.com/r-lib/ps/issues
# Encoding: UTF-8
# Depends: R (>= 3.1)
# Imports: utils
# Suggests: callr, covr, curl, pingr, processx (>= 3.1.0), R6, rlang, testthat, tibble
# RoxygenNote: 7.0.2.9000
# Biarch: true
# NeedsCompilation: yes
# Packaged: 2020-02-12 09:40:34 UTC; gaborcsardi
# Author: Jay Loden [aut], Dave Daeschler [aut], Giampaolo Rodola' [aut], Gabor Csardi [aut, cre], RStudio [cph]
# Maintainer: Gabor Csardi <csardi.gabor@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-02-12 12:10:03 UTC
